# Jazzy configuration for OpenCoreLocation
# Version will be dynamically set by generate-docs.sh script

module: OpenCoreLocation
author: Ezequiel (Kimi) Aceto
github_url: https://github.com/eaceto/OpenCoreLocation
output: docs
clean: true
readme: README.md
swift_build_tool: spm
min_acl: public
theme: fullwidth