name: Generate Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: macos-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git tags
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    
    - name: Install Jazzy via Homebrew
      run: |
        echo "Installing Jazzy via Homebrew..."
        brew install jazzy
        jazzy --version
      
    - name: Make scripts executable
      run: chmod +x scripts/generate-docs.sh
      
    - name: Generate Documentation
      run: |
        echo "Generating documentation with automatic version detection..."
        make docs
      
    - name: Verify Documentation
      run: |
        echo "Verifying documentation was generated..."
        if [ -f "docs/index.html" ]; then
          echo "✅ Documentation generated successfully"
          ls -la docs/
        else
          echo "❌ Documentation generation failed - index.html not found"
          exit 1
        fi
      
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
        
    - name: Setup Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      uses: actions/configure-pages@v3
      
    - name: Add .nojekyll file
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: |
        echo "Adding .nojekyll file to disable Jekyll processing..."
        touch docs/.nojekyll
        
    - name: Upload to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v2