name: Generate Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for git tags
      
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    
    - name: Install Xcode Command Line Tools
      run: |
        echo "Ensuring Xcode command line tools are available..."
        sudo xcode-select --install || true
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        
    - name: Install Jazzy using system approach
      run: |
        echo "Installing Jazzy using system Ruby..."
        # Use system Ruby and install Jazzy directly
        /usr/bin/ruby -v
        sudo /usr/bin/gem install jazzy --no-document
        jazzy --version
      
    - name: Make scripts executable
      run: chmod +x scripts/generate-docs.sh
      
    - name: Generate Documentation
      run: |
        echo "Generating documentation with automatic version detection..."
        # Auto-detect version from git tags
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [[ -z "$VERSION" ]]; then
            COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "dev")
            VERSION="dev-${COMMIT_HASH}"
        fi
        echo "Using version: $VERSION"
        
        # Generate documentation using system jazzy
        jazzy --config .jazzy.yaml --module-version "$VERSION"
      
    - name: Verify Documentation
      run: |
        echo "Verifying documentation was generated..."
        if [ -f "docs/index.html" ]; then
          echo "✅ Documentation generated successfully"
          ls -la docs/
        else
          echo "❌ Documentation generation failed - index.html not found"
          exit 1
        fi
      
    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
        
    - name: Setup Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      uses: actions/configure-pages@v4
      
    - name: Add .nojekyll file
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      run: |
        echo "Adding .nojekyll file to disable Jekyll processing..."
        touch docs/.nojekyll
        
    - name: Upload to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
        
    - name: Deploy to GitHub Pages
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      id: deployment
      uses: actions/deploy-pages@v4